services:
  # Servicio web principal - FastAPI
  - type: web
    name: gymapi
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: gymapi-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: gymapi-redis
          type: redis
          property: connectionString
      # Otras variables de entorno deben configurarse manualmente en el panel de Render
      - key: SECRET_KEY
        generateValue: true  # Genera una clave segura automáticamente
      - key: DEBUG_MODE
        value: "True"  # Cambiado a True para activar el modo debug
      - key: LOGGING_LEVEL
        value: "DEBUG"  # Añadido nivel de logging detallado
      - key: PYTHONUNBUFFERED
        value: "1"  # Evita buffering en la salida de Python
      - key: SQLALCHEMY_ECHO
        value: "True"  # Muestra consultas SQL en la consola

  # Servicio Redis
  - type: redis
    name: gymapi-redis
    ipAllowList: # IP permitidas para conectarse a Redis
      - source: 0.0.0.0/0
        description: everywhere
    plan: starter # Elige el plan según tus necesidades

# Base de datos PostgreSQL
databases:
  - name: gymapi-db
    databaseName: gymapi
    user: gymapi_user
    plan: starter # Elige el plan según tus necesidades 