services:
  # Servicio web principal - FastAPI
  - type: web
    name: gymapi
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: gymapi-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: gymapi-redis
          type: redis
          property: connectionString
      # Otras variables de entorno deben configurarse manualmente en el panel de Render
      - key: SECRET_KEY
        generateValue: true  # Genera una clave segura automáticamente
      - key: DEBUG_MODE
        value: "False"

  # Servicio Redis
  - type: redis
    name: gymapi-redis
    ipAllowList: # IP permitidas para conectarse a Redis
      - source: 0.0.0.0/0
        description: everywhere
    plan: starter # Elige el plan según tus necesidades

# Base de datos PostgreSQL
databases:
  - name: gymapi-db
    databaseName: gymapi
    user: gymapi_user
    plan: starter # Elige el plan según tus necesidades 