"""Refactor schedule models and add unique constraint

Revision ID: 402f9b8ef40e
Revises: 7ec429c792cf
Create Date: 2025-04-11 01:41:06.678713

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '402f9b8ef40e'
down_revision = '7ec429c792cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gym_special_hours', 'date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
    op.create_index(op.f('ix_gym_special_hours_gym_id'), 'gym_special_hours', ['gym_id'], unique=False)
    op.create_unique_constraint('uq_gym_special_hours_gym_date', 'gym_special_hours', ['gym_id', 'date'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_gym_special_hours_gym_date', 'gym_special_hours', type_='unique')
    op.drop_index(op.f('ix_gym_special_hours_gym_id'), table_name='gym_special_hours')
    op.alter_column('gym_special_hours', 'date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ### 