"""Add last_message fields to chat_rooms

Revision ID: 459b732a1509
Revises: af51e38e1aaf
Create Date: 2025-07-31 15:15:45.010648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '459b732a1509'
down_revision = 'af51e38e1aaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### Los campos ya existen en la BD, no hacer nada ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_chat_rooms_last_message_sender_id', 'chat_rooms', type_='foreignkey')
    op.drop_index(op.f('ix_chat_rooms_last_message_sender_id'), table_name='chat_rooms')
    op.drop_column('chat_rooms', 'last_message_type')
    op.drop_column('chat_rooms', 'last_message_sender_id')
    op.drop_column('chat_rooms', 'last_message_text')
    op.drop_column('chat_rooms', 'last_message_at')
    # ### end Alembic commands ### 