"""agregar_categorias_personalizadas_de_clases

Revision ID: 4dfcdddc1734
Revises: 82965e847bc2
Create Date: 2025-03-31 14:30:15.399920

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4dfcdddc1734'
down_revision = '82965e847bc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gym_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=False),
    sa.Column('close_time', sa.Time(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('day_of_week >= 0 AND day_of_week <= 6', name='check_valid_day_of_week'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gym_hours_id'), 'gym_hours', ['id'], unique=False)
    op.create_table('class_category_custom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_category_custom_id'), 'class_category_custom', ['id'], unique=False)
    op.create_table('gym_special_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gym_special_hours_date'), 'gym_special_hours', ['date'], unique=False)
    op.create_index(op.f('ix_gym_special_hours_id'), 'gym_special_hours', ['id'], unique=False)
    op.create_table('class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('max_capacity', sa.Integer(), nullable=False),
    sa.Column('difficulty_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='classdifficultyLevel'), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('category_enum', sa.Enum('CARDIO', 'STRENGTH', 'FLEXIBILITY', 'HIIT', 'YOGA', 'PILATES', 'FUNCTIONAL', 'OTHER', name='classcategory'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['class_category_custom.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_id'), 'class', ['id'], unique=False)
    op.create_table('class_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('room', sa.String(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('recurrence_pattern', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='classsessionstatus'), nullable=True),
    sa.Column('current_participants', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_session_id'), 'class_session', ['id'], unique=False)
    op.create_index(op.f('ix_class_session_start_time'), 'class_session', ['start_time'], unique=False)
    op.create_table('class_participation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('REGISTERED', 'ATTENDED', 'CANCELLED', 'NO_SHOW', name='classparticipationstatus'), nullable=True),
    sa.Column('registration_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('attendance_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['class_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_participation_id'), 'class_participation', ['id'], unique=False)
    # Eliminamos las conversiones de tipo que causan problemas
    # op.alter_column('user', 'role', ...)
    # op.alter_column('user', 'birth_date', ...)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Eliminamos las conversiones de tipo que causan problemas
    # op.alter_column('user', 'birth_date', ...)
    # op.alter_column('user', 'role', ...)
    op.drop_index(op.f('ix_class_participation_id'), table_name='class_participation')
    op.drop_table('class_participation')
    op.drop_index(op.f('ix_class_session_start_time'), table_name='class_session')
    op.drop_index(op.f('ix_class_session_id'), table_name='class_session')
    op.drop_table('class_session')
    op.drop_index(op.f('ix_class_id'), table_name='class')
    op.drop_table('class')
    op.drop_index(op.f('ix_gym_special_hours_id'), table_name='gym_special_hours')
    op.drop_index(op.f('ix_gym_special_hours_date'), table_name='gym_special_hours')
    op.drop_table('gym_special_hours')
    op.drop_index(op.f('ix_class_category_custom_id'), table_name='class_category_custom')
    op.drop_table('class_category_custom')
    op.drop_index(op.f('ix_gym_hours_id'), table_name='gym_hours')
    op.drop_table('gym_hours')
    # ### end Alembic commands ### 