"""add_max_billing_cycles_to_membership_plans

Revision ID: 7b04db828651
Revises: b0a037166a72
Create Date: 2025-07-08 23:58:33.321768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b04db828651'
down_revision = 'b0a037166a72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('membership_plans', sa.Column('max_billing_cycles', sa.Integer(), nullable=True))
    op.alter_column('nutrition_plans', 'is_live_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('nutrition_plans', 'live_participants_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nutrition_plans', 'live_participants_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('nutrition_plans', 'is_live_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('membership_plans', 'max_billing_cycles')
    # ### end Alembic commands ### 