"""Allow null open_time and close_time in gym_hours

Revision ID: 7ec429c792cf
Revises: 582fee459713
Create Date: 2025-04-11 01:18:26.730741

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ec429c792cf'
down_revision = '582fee459713'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gym_hours', 'open_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('gym_hours', 'close_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gym_hours', 'close_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('gym_hours', 'open_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    # ### end Alembic commands ### 