"""replace_full_name_with_first_and_last_name

Revision ID: 8fa7bead798f
Revises: c16c8f190e02
Create Date: 2025-04-09 12:45:09.197455

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8fa7bead798f'
down_revision = 'c16c8f190e02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Parte 1: Agregar nuevas columnas y migrar datos
    op.add_column('user', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(), nullable=True))
    
    # Transferir datos: dividir full_name en first_name y last_name
    connection = op.get_bind()
    users = connection.execute(sa.text("SELECT id, full_name FROM \"user\" WHERE full_name IS NOT NULL"))
    
    for user_id, full_name in users:
        # Dividir el nombre completo en nombre y apellido
        name_parts = full_name.split(" ", 1)
        first_name = name_parts[0] if len(name_parts) > 0 else ""
        last_name = name_parts[1] if len(name_parts) > 1 else ""
        
        # Actualizar el usuario con el nombre y apellido
        connection.execute(
            sa.text(
                "UPDATE \"user\" SET first_name = :first_name, last_name = :last_name WHERE id = :user_id"
            ),
            {"first_name": first_name, "last_name": last_name, "user_id": user_id}
        )
    
    # Crear índices para las nuevas columnas
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    
    # Parte 2: Eliminar columna antigua
    op.drop_index('ix_user_full_name', table_name='user')
    op.drop_column('user', 'full_name')
    
    # Omitimos los cambios de tipo que causaron error
    # op.alter_column('user', 'role', ... )
    # op.alter_column('user', 'birth_date', ... )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Parte 1: Restaurar columna full_name
    op.add_column('user', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    
    # Reconstruir full_name a partir de first_name y last_name
    connection = op.get_bind()
    users = connection.execute(sa.text("SELECT id, first_name, last_name FROM \"user\""))
    
    for user_id, first_name, last_name in users:
        # Construir el nombre completo
        full_name = f"{first_name or ''} {last_name or ''}".strip()
        
        # Actualizar el usuario con el nombre completo reconstruido
        connection.execute(
            sa.text("UPDATE \"user\" SET full_name = :full_name WHERE id = :user_id"),
            {"full_name": full_name, "user_id": user_id}
        )
    
    # Crear índice para full_name
    op.create_index('ix_user_full_name', 'user', ['full_name'], unique=False)
    
    # Parte 2: Eliminar columnas nuevas
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    
    # Omitimos los cambios de tipo que causaron error
    # op.alter_column('user', 'birth_date', ... )
    # op.alter_column('user', 'role', ... )
    # ### end Alembic commands ### 