"""add_updated_at_to_chat_rooms

Revision ID: a091ab4089d2
Revises: a9730a268424
Create Date: 2025-06-24 20:25:11.307850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a091ab4089d2'
down_revision = 'a9730a268424'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_rooms', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_rooms', 'updated_at')
    # ### end Alembic commands ### 