"""add_membership_system

Revision ID: a9730a268424
Revises: a762df8c3a1e
Create Date: 2025-06-23 16:52:51.844184

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a9730a268424'
down_revision = 'a762df8c3a1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('membership_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gym_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('billing_interval', sa.String(length=20), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('stripe_price_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_product_id', sa.String(length=255), nullable=True),
    sa.Column('features', sa.Text(), nullable=True),
    sa.Column('max_bookings_per_month', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_membership_plans_gym_id'), 'membership_plans', ['gym_id'], unique=False)
    op.create_index(op.f('ix_membership_plans_id'), 'membership_plans', ['id'], unique=False)
    op.create_index(op.f('ix_membership_plans_is_active'), 'membership_plans', ['is_active'], unique=False)
    op.create_index(op.f('ix_membership_plans_stripe_price_id'), 'membership_plans', ['stripe_price_id'], unique=True)
    op.create_index(op.f('ix_membership_plans_stripe_product_id'), 'membership_plans', ['stripe_product_id'], unique=False)
    
    # Fix chat/events changes
    op.alter_column('chat_members', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('chat_rooms', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'CLOSED', name='chatroomstatus'),
               nullable=True,
               existing_server_default=sa.text("'ACTIVE'::chatroomstatus"))
    op.alter_column('events', 'completion_attempts',
               existing_type=sa.INTEGER(),
               comment='Número de intentos fallidos de marcar el evento como completado',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index('ix_events_completion_attempts', table_name='events')
    op.drop_constraint('user_qr_code_key', 'user', type_='unique')
    op.create_index(op.f('ix_user_qr_code'), 'user', ['qr_code'], unique=True)
    
    # Add membership columns to user_gyms with proper handling of existing data
    
    # 1. Add columns as nullable first
    op.add_column('user_gyms', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('user_gyms', sa.Column('membership_expires_at', sa.DateTime(), nullable=True))
    op.add_column('user_gyms', sa.Column('membership_type', sa.String(length=50), nullable=True))
    op.add_column('user_gyms', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.add_column('user_gyms', sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
    op.add_column('user_gyms', sa.Column('last_payment_at', sa.DateTime(), nullable=True))
    op.add_column('user_gyms', sa.Column('notes', sa.String(length=500), nullable=True))
    
    # 2. Update existing records with default values
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE user_gyms 
        SET 
            is_active = true,
            membership_type = 'free'
        WHERE is_active IS NULL OR membership_type IS NULL
    """))
    
    # 3. Make required columns NOT NULL after setting defaults
    op.alter_column('user_gyms', 'is_active', nullable=False)
    op.alter_column('user_gyms', 'membership_type', nullable=False)
    
    # 4. Create indexes
    op.create_index(op.f('ix_user_gyms_is_active'), 'user_gyms', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_gyms_membership_expires_at'), 'user_gyms', ['membership_expires_at'], unique=False)
    op.create_index(op.f('ix_user_gyms_stripe_customer_id'), 'user_gyms', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_user_gyms_stripe_subscription_id'), 'user_gyms', ['stripe_subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_gyms_stripe_subscription_id'), table_name='user_gyms')
    op.drop_index(op.f('ix_user_gyms_stripe_customer_id'), table_name='user_gyms')
    op.drop_index(op.f('ix_user_gyms_membership_expires_at'), table_name='user_gyms')
    op.drop_index(op.f('ix_user_gyms_is_active'), table_name='user_gyms')
    op.drop_column('user_gyms', 'notes')
    op.drop_column('user_gyms', 'last_payment_at')
    op.drop_column('user_gyms', 'stripe_subscription_id')
    op.drop_column('user_gyms', 'stripe_customer_id')
    op.drop_column('user_gyms', 'membership_type')
    op.drop_column('user_gyms', 'membership_expires_at')
    op.drop_column('user_gyms', 'is_active')
    op.drop_index(op.f('ix_user_qr_code'), table_name='user')
    op.create_unique_constraint('user_qr_code_key', 'user', ['qr_code'])
    op.create_index('ix_events_completion_attempts', 'events', ['completion_attempts'], unique=False)
    op.alter_column('events', 'completion_attempts',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Número de intentos fallidos de marcar el evento como completado',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('chat_rooms', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'CLOSED', name='chatroomstatus'),
               nullable=False,
               existing_server_default=sa.text("'ACTIVE'::chatroomstatus"))
    op.alter_column('chat_members', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_membership_plans_stripe_product_id'), table_name='membership_plans')
    op.drop_index(op.f('ix_membership_plans_stripe_price_id'), table_name='membership_plans')
    op.drop_index(op.f('ix_membership_plans_is_active'), table_name='membership_plans')
    op.drop_index(op.f('ix_membership_plans_id'), table_name='membership_plans')
    op.drop_index(op.f('ix_membership_plans_gym_id'), table_name='membership_plans')
    op.drop_table('membership_plans')
    # ### end Alembic commands ### 