"""add_timezone_to_gym_table

Revision ID: af51e38e1aaf
Revises: ea4b311a45fb
Create Date: 2025-07-27 14:07:01.919483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af51e38e1aaf'
down_revision = 'ea4b311a45fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Agregar columna timezone con valor temporal nullable
    op.add_column('gyms', sa.Column('timezone', sa.String(length=50), nullable=True))
    
    # Establecer UTC como valor por defecto para gimnasios existentes
    op.execute("UPDATE gyms SET timezone = 'UTC' WHERE timezone IS NULL")
    
    # Hacer la columna NOT NULL después de establecer los valores
    op.alter_column('gyms', 'timezone', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gyms', 'timezone')
    # ### end Alembic commands ### 