"""add_subscription_id_to_stripe_profiles

Revision ID: b0f5a7507642
Revises: a1b2c3d4e5f6
Create Date: 2025-07-10 22:19:18.088221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0f5a7507642'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_gym_stripe_profiles', sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_user_gym_stripe_profiles_stripe_subscription_id'), 'user_gym_stripe_profiles', ['stripe_subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_gym_stripe_profiles_stripe_subscription_id'), table_name='user_gym_stripe_profiles')
    op.drop_column('user_gym_stripe_profiles', 'stripe_subscription_id')
    # ### end Alembic commands ### 