"""add_nutrition_system

Revision ID: b394dbb765a5
Revises: e1c3c9ad31f2
Create Date: 2025-07-03 23:56:57.450981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b394dbb765a5'
down_revision = 'e1c3c9ad31f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutrition_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('goal', sa.Enum('BULK', 'CUT', 'MAINTENANCE', 'WEIGHT_LOSS', 'MUSCLE_GAIN', 'PERFORMANCE', name='nutritiongoal'), nullable=False),
    sa.Column('difficulty_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='difficultylevel'), nullable=True),
    sa.Column('budget_level', sa.Enum('ECONOMIC', 'MEDIUM', 'PREMIUM', name='budgetlevel'), nullable=True),
    sa.Column('dietary_restrictions', sa.Enum('NONE', 'VEGETARIAN', 'VEGAN', 'GLUTEN_FREE', 'LACTOSE_FREE', 'KETO', 'PALEO', 'MEDITERRANEAN', name='dietaryrestriction'), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('target_calories', sa.Integer(), nullable=True),
    sa.Column('target_protein_g', sa.Float(), nullable=True),
    sa.Column('target_carbs_g', sa.Float(), nullable=True),
    sa.Column('target_fat_g', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('gym_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrition_plans_creator_id'), 'nutrition_plans', ['creator_id'], unique=False)
    op.create_index(op.f('ix_nutrition_plans_goal'), 'nutrition_plans', ['goal'], unique=False)
    op.create_index(op.f('ix_nutrition_plans_gym_id'), 'nutrition_plans', ['gym_id'], unique=False)
    op.create_index(op.f('ix_nutrition_plans_id'), 'nutrition_plans', ['id'], unique=False)
    op.create_index(op.f('ix_nutrition_plans_is_active'), 'nutrition_plans', ['is_active'], unique=False)
    op.create_table('daily_nutrition_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nutrition_plan_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('planned_date', sa.DateTime(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('total_calories', sa.Integer(), nullable=True),
    sa.Column('total_protein_g', sa.Float(), nullable=True),
    sa.Column('total_carbs_g', sa.Float(), nullable=True),
    sa.Column('total_fat_g', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nutrition_plan_id'], ['nutrition_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_nutrition_plans_id'), 'daily_nutrition_plans', ['id'], unique=False)
    op.create_index(op.f('ix_daily_nutrition_plans_is_published'), 'daily_nutrition_plans', ['is_published'], unique=False)
    op.create_index(op.f('ix_daily_nutrition_plans_nutrition_plan_id'), 'daily_nutrition_plans', ['nutrition_plan_id'], unique=False)
    op.create_index(op.f('ix_daily_nutrition_plans_planned_date'), 'daily_nutrition_plans', ['planned_date'], unique=False)
    op.create_table('nutrition_plan_followers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('notification_time_breakfast', sa.String(length=5), nullable=True),
    sa.Column('notification_time_lunch', sa.String(length=5), nullable=True),
    sa.Column('notification_time_dinner', sa.String(length=5), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['nutrition_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrition_plan_followers_id'), 'nutrition_plan_followers', ['id'], unique=False)
    op.create_index(op.f('ix_nutrition_plan_followers_is_active'), 'nutrition_plan_followers', ['is_active'], unique=False)
    op.create_index(op.f('ix_nutrition_plan_followers_plan_id'), 'nutrition_plan_followers', ['plan_id'], unique=False)
    op.create_index(op.f('ix_nutrition_plan_followers_user_id'), 'nutrition_plan_followers', ['user_id'], unique=False)
    op.create_table('meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_plan_id', sa.Integer(), nullable=False),
    sa.Column('meal_type', sa.Enum('BREAKFAST', 'MID_MORNING', 'LUNCH', 'AFTERNOON', 'DINNER', 'POST_WORKOUT', 'LATE_SNACK', name='mealtype'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('preparation_time_minutes', sa.Integer(), nullable=True),
    sa.Column('cooking_instructions', sa.Text(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('protein_g', sa.Float(), nullable=True),
    sa.Column('carbs_g', sa.Float(), nullable=True),
    sa.Column('fat_g', sa.Float(), nullable=True),
    sa.Column('fiber_g', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('order_in_day', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['daily_plan_id'], ['daily_nutrition_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meals_daily_plan_id'), 'meals', ['daily_plan_id'], unique=False)
    op.create_index(op.f('ix_meals_id'), 'meals', ['id'], unique=False)
    op.create_index(op.f('ix_meals_meal_type'), 'meals', ['meal_type'], unique=False)
    op.create_table('user_daily_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('daily_plan_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('meals_completed', sa.Integer(), nullable=True),
    sa.Column('total_meals', sa.Integer(), nullable=False),
    sa.Column('completion_percentage', sa.Float(), nullable=True),
    sa.Column('overall_satisfaction', sa.Integer(), nullable=True),
    sa.Column('difficulty_rating', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('body_fat_percentage', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['daily_plan_id'], ['daily_nutrition_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_daily_progress_daily_plan_id'), 'user_daily_progress', ['daily_plan_id'], unique=False)
    op.create_index(op.f('ix_user_daily_progress_date'), 'user_daily_progress', ['date'], unique=False)
    op.create_index(op.f('ix_user_daily_progress_id'), 'user_daily_progress', ['id'], unique=False)
    op.create_index(op.f('ix_user_daily_progress_user_id'), 'user_daily_progress', ['user_id'], unique=False)
    op.create_table('meal_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('alternatives', sa.Text(), nullable=True),
    sa.Column('is_optional', sa.Boolean(), nullable=True),
    sa.Column('calories_per_serving', sa.Integer(), nullable=True),
    sa.Column('protein_per_serving', sa.Float(), nullable=True),
    sa.Column('carbs_per_serving', sa.Float(), nullable=True),
    sa.Column('fat_per_serving', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_ingredients_id'), 'meal_ingredients', ['id'], unique=False)
    op.create_index(op.f('ix_meal_ingredients_meal_id'), 'meal_ingredients', ['meal_id'], unique=False)
    op.create_table('user_meal_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('satisfaction_rating', sa.Integer(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ingredients_modified', sa.Text(), nullable=True),
    sa.Column('portion_size_modifier', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_meal_completions_completed_at'), 'user_meal_completions', ['completed_at'], unique=False)
    op.create_index(op.f('ix_user_meal_completions_id'), 'user_meal_completions', ['id'], unique=False)
    op.create_index(op.f('ix_user_meal_completions_meal_id'), 'user_meal_completions', ['meal_id'], unique=False)
    op.create_index(op.f('ix_user_meal_completions_user_id'), 'user_meal_completions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_meal_completions_user_id'), table_name='user_meal_completions')
    op.drop_index(op.f('ix_user_meal_completions_meal_id'), table_name='user_meal_completions')
    op.drop_index(op.f('ix_user_meal_completions_id'), table_name='user_meal_completions')
    op.drop_index(op.f('ix_user_meal_completions_completed_at'), table_name='user_meal_completions')
    op.drop_table('user_meal_completions')
    op.drop_index(op.f('ix_meal_ingredients_meal_id'), table_name='meal_ingredients')
    op.drop_index(op.f('ix_meal_ingredients_id'), table_name='meal_ingredients')
    op.drop_table('meal_ingredients')
    op.drop_index(op.f('ix_user_daily_progress_user_id'), table_name='user_daily_progress')
    op.drop_index(op.f('ix_user_daily_progress_id'), table_name='user_daily_progress')
    op.drop_index(op.f('ix_user_daily_progress_date'), table_name='user_daily_progress')
    op.drop_index(op.f('ix_user_daily_progress_daily_plan_id'), table_name='user_daily_progress')
    op.drop_table('user_daily_progress')
    op.drop_index(op.f('ix_meals_meal_type'), table_name='meals')
    op.drop_index(op.f('ix_meals_id'), table_name='meals')
    op.drop_index(op.f('ix_meals_daily_plan_id'), table_name='meals')
    op.drop_table('meals')
    op.drop_index(op.f('ix_nutrition_plan_followers_user_id'), table_name='nutrition_plan_followers')
    op.drop_index(op.f('ix_nutrition_plan_followers_plan_id'), table_name='nutrition_plan_followers')
    op.drop_index(op.f('ix_nutrition_plan_followers_is_active'), table_name='nutrition_plan_followers')
    op.drop_index(op.f('ix_nutrition_plan_followers_id'), table_name='nutrition_plan_followers')
    op.drop_table('nutrition_plan_followers')
    op.drop_index(op.f('ix_daily_nutrition_plans_planned_date'), table_name='daily_nutrition_plans')
    op.drop_index(op.f('ix_daily_nutrition_plans_nutrition_plan_id'), table_name='daily_nutrition_plans')
    op.drop_index(op.f('ix_daily_nutrition_plans_is_published'), table_name='daily_nutrition_plans')
    op.drop_index(op.f('ix_daily_nutrition_plans_id'), table_name='daily_nutrition_plans')
    op.drop_table('daily_nutrition_plans')
    op.drop_index(op.f('ix_nutrition_plans_is_active'), table_name='nutrition_plans')
    op.drop_index(op.f('ix_nutrition_plans_id'), table_name='nutrition_plans')
    op.drop_index(op.f('ix_nutrition_plans_gym_id'), table_name='nutrition_plans')
    op.drop_index(op.f('ix_nutrition_plans_goal'), table_name='nutrition_plans')
    op.drop_index(op.f('ix_nutrition_plans_creator_id'), table_name='nutrition_plans')
    op.drop_table('nutrition_plans')
    # ### end Alembic commands ### 