"""Add gym_id field to schedule models for multi-tenant

Revision ID: c16c8f190e02
Revises: e3a222984865
Create Date: 2025-04-09 02:09:55.080555

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c16c8f190e02'
down_revision = 'e3a222984865'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. ClassParticipation - añadir gym_id
    op.add_column('class_participation', sa.Column('gym_id', sa.Integer(), nullable=True))
    op.execute("UPDATE class_participation SET gym_id = 1")
    op.alter_column('class_participation', 'gym_id', nullable=False)
    op.create_foreign_key(None, 'class_participation', 'gyms', ['gym_id'], ['id'])
    
    # 2. GymHours - añadir gym_id
    op.add_column('gym_hours', sa.Column('gym_id', sa.Integer(), nullable=True))
    op.execute("UPDATE gym_hours SET gym_id = 1")
    op.alter_column('gym_hours', 'gym_id', nullable=False)
    op.create_foreign_key(None, 'gym_hours', 'gyms', ['gym_id'], ['id'])
    
    # 3. GymSpecialHours - añadir gym_id
    op.add_column('gym_special_hours', sa.Column('gym_id', sa.Integer(), nullable=True))
    op.execute("UPDATE gym_special_hours SET gym_id = 1")
    op.alter_column('gym_special_hours', 'gym_id', nullable=False)
    op.create_foreign_key(None, 'gym_special_hours', 'gyms', ['gym_id'], ['id'])
    
    # Eliminamos los cambios en user que no son parte de este proceso
    # op.alter_column('user', 'role',
    #            existing_type=sa.VARCHAR(length=10),
    #            type_=sa.Enum('ADMIN', 'TRAINER', 'MEMBER', name='userrole'),
    #            existing_nullable=True,
    #            existing_server_default=sa.text("'member'::character varying"))
    # op.alter_column('user', 'birth_date',
    #            existing_type=postgresql.TIMESTAMP(timezone=True),
    #            type_=sa.DateTime(),
    #            existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Eliminamos los cambios en user que no son parte de este proceso
    # op.alter_column('user', 'birth_date',
    #            existing_type=sa.DateTime(),
    #            type_=postgresql.TIMESTAMP(timezone=True),
    #            existing_nullable=True)
    # op.alter_column('user', 'role',
    #            existing_type=sa.Enum('ADMIN', 'TRAINER', 'MEMBER', name='userrole'),
    #            type_=sa.VARCHAR(length=10),
    #            existing_nullable=True,
    #            existing_server_default=sa.text("'member'::character varying"))
    
    # GymSpecialHours
    op.drop_constraint(None, 'gym_special_hours', type_='foreignkey')
    op.drop_column('gym_special_hours', 'gym_id')
    
    # GymHours
    op.drop_constraint(None, 'gym_hours', type_='foreignkey')
    op.drop_column('gym_hours', 'gym_id')
    
    # ClassParticipation
    op.drop_constraint(None, 'class_participation', type_='foreignkey')
    op.drop_column('class_participation', 'gym_id')
    # ### end Alembic commands ### 