"""add_health_tracking_tables

Revision ID: cebae10190ed
Revises: 7220aa4baad6
Create Date: 2025-08-05 23:54:37.736398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cebae10190ed'
down_revision = '7220aa4baad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gym_id', sa.Integer(), nullable=False),
    sa.Column('achievement_type', sa.Enum('ATTENDANCE_STREAK', 'WEIGHT_GOAL', 'CLASS_MILESTONE', 'SOCIAL_ENGAGEMENT', 'STRENGTH_GAIN', 'ENDURANCE_MILESTONE', 'CONSISTENCY', name='achievementtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Título del logro'),
    sa.Column('description', sa.Text(), nullable=False, comment='Descripción del logro'),
    sa.Column('icon', sa.String(length=100), nullable=False, comment='Emoji o código de icono'),
    sa.Column('value', sa.Float(), nullable=False, comment='Valor numérico del logro (ej: 30 días, 10kg)'),
    sa.Column('unit', sa.String(length=50), nullable=True, comment='Unidad del valor'),
    sa.Column('rarity', sa.String(length=50), nullable=True, comment='Rareza: common, rare, epic, legendary'),
    sa.Column('earned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_milestone', sa.Boolean(), nullable=True, comment='Si es un hito importante'),
    sa.Column('points_awarded', sa.Integer(), nullable=True, comment='Puntos otorgados por el logro'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_achievements_gym_id'), 'user_achievements', ['gym_id'], unique=False)
    op.create_index(op.f('ix_user_achievements_id'), 'user_achievements', ['id'], unique=False)
    op.create_index(op.f('ix_user_achievements_user_id'), 'user_achievements', ['user_id'], unique=False)
    op.create_table('user_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gym_id', sa.Integer(), nullable=False),
    sa.Column('goal_type', sa.Enum('WEIGHT_LOSS', 'WEIGHT_GAIN', 'MUSCLE_GAIN', 'BODY_FAT_LOSS', 'ENDURANCE', 'STRENGTH', 'ATTENDANCE', 'NUTRITION', name='goaltype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Título personalizado del objetivo'),
    sa.Column('description', sa.Text(), nullable=True, comment='Descripción detallada'),
    sa.Column('target_value', sa.Float(), nullable=False, comment='Valor objetivo a alcanzar'),
    sa.Column('current_value', sa.Float(), nullable=False, comment='Valor actual'),
    sa.Column('start_value', sa.Float(), nullable=True, comment='Valor inicial al crear el objetivo'),
    sa.Column('unit', sa.String(length=50), nullable=False, comment='Unidad de medida (kg, lbs, reps, minutes)'),
    sa.Column('target_date', sa.Date(), nullable=True, comment='Fecha objetivo para completar'),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'PAUSED', 'CANCELLED', 'EXPIRED', name='goalstatus'), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True, comment='Si el objetivo es público a otros miembros'),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=True, comment='Notificaciones de progreso'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_goals_gym_id'), 'user_goals', ['gym_id'], unique=False)
    op.create_index(op.f('ix_user_goals_id'), 'user_goals', ['id'], unique=False)
    op.create_index(op.f('ix_user_goals_user_id'), 'user_goals', ['user_id'], unique=False)
    op.create_table('user_health_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gym_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True, comment='Peso en kg'),
    sa.Column('body_fat_percentage', sa.Float(), nullable=True, comment='Porcentaje de grasa corporal'),
    sa.Column('muscle_mass', sa.Float(), nullable=True, comment='Masa muscular en kg'),
    sa.Column('visceral_fat', sa.Float(), nullable=True, comment='Grasa visceral'),
    sa.Column('bone_mass', sa.Float(), nullable=True, comment='Masa ósea en kg'),
    sa.Column('water_percentage', sa.Float(), nullable=True, comment='Porcentaje de agua corporal'),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('measurement_type', sa.Enum('MANUAL', 'SCALE', 'TRAINER', 'DEVICE', name='measurementtype'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True, comment='Notas adicionales sobre la medición'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_health_records_gym_id'), 'user_health_records', ['gym_id'], unique=False)
    op.create_index(op.f('ix_user_health_records_id'), 'user_health_records', ['id'], unique=False)
    op.create_index(op.f('ix_user_health_records_user_id'), 'user_health_records', ['user_id'], unique=False)
    op.create_table('user_health_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gym_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('body_fat_percentage', sa.Float(), nullable=True),
    sa.Column('muscle_mass', sa.Float(), nullable=True),
    sa.Column('weekly_workouts', sa.Integer(), nullable=True, comment='Entrenamientos en la semana'),
    sa.Column('current_streak', sa.Integer(), nullable=True, comment='Racha actual de días activos'),
    sa.Column('classes_attended_week', sa.Integer(), nullable=True),
    sa.Column('total_workout_minutes_week', sa.Integer(), nullable=True),
    sa.Column('social_score', sa.Float(), nullable=True, comment='Score social calculado'),
    sa.Column('chat_messages_week', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Snapshots diarios para análisis de tendencias y performance del dashboard'
    )
    op.create_index(op.f('ix_user_health_snapshots_gym_id'), 'user_health_snapshots', ['gym_id'], unique=False)
    op.create_index(op.f('ix_user_health_snapshots_id'), 'user_health_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_user_health_snapshots_snapshot_date'), 'user_health_snapshots', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_user_health_snapshots_user_id'), 'user_health_snapshots', ['user_id'], unique=False)
    op.drop_index(op.f('ix_chat_member_user_room'), table_name='chat_members')
    op.drop_index(op.f('ix_class_participation_member_gym_attended'), table_name='class_participation', postgresql_where="(status = 'ATTENDED'::classparticipationstatus)")
    op.drop_index(op.f('ix_event_participation_member_gym_date'), table_name='event_participations')
    op.drop_column('user', 'goals')
    op.drop_index(op.f('ix_user_gym_user_gym_created'), table_name='user_gyms')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_gym_user_gym_created'), 'user_gyms', ['user_id', 'gym_id', 'created_at'], unique=False)
    op.add_column('user', sa.Column('goals', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_event_participation_member_gym_date'), 'event_participations', ['member_id', 'gym_id', 'attended'], unique=False)
    op.create_index(op.f('ix_class_participation_member_gym_attended'), 'class_participation', ['member_id', 'gym_id', 'created_at'], unique=False, postgresql_where="(status = 'ATTENDED'::classparticipationstatus)")
    op.create_index(op.f('ix_chat_member_user_room'), 'chat_members', ['user_id', 'room_id'], unique=False)
    op.drop_index(op.f('ix_user_health_snapshots_user_id'), table_name='user_health_snapshots')
    op.drop_index(op.f('ix_user_health_snapshots_snapshot_date'), table_name='user_health_snapshots')
    op.drop_index(op.f('ix_user_health_snapshots_id'), table_name='user_health_snapshots')
    op.drop_index(op.f('ix_user_health_snapshots_gym_id'), table_name='user_health_snapshots')
    op.drop_table('user_health_snapshots')
    op.drop_index(op.f('ix_user_health_records_user_id'), table_name='user_health_records')
    op.drop_index(op.f('ix_user_health_records_id'), table_name='user_health_records')
    op.drop_index(op.f('ix_user_health_records_gym_id'), table_name='user_health_records')
    op.drop_table('user_health_records')
    op.drop_index(op.f('ix_user_goals_user_id'), table_name='user_goals')
    op.drop_index(op.f('ix_user_goals_id'), table_name='user_goals')
    op.drop_index(op.f('ix_user_goals_gym_id'), table_name='user_goals')
    op.drop_table('user_goals')
    op.drop_index(op.f('ix_user_achievements_user_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_gym_id'), table_name='user_achievements')
    op.drop_table('user_achievements')
    # ### end Alembic commands ### 