"""Add nutrition safety screening tables

Revision ID: d2f3930aa2b1
Revises: 603ffe2d2733
Create Date: 2025-12-29 09:22:22.520529

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd2f3930aa2b1'
down_revision = '603ffe2d2733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutrition_safety_screenings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gym_id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=False),
    sa.Column('medical_conditions', sa.JSON(), nullable=True),
    sa.Column('is_pregnant', sa.Boolean(), nullable=False),
    sa.Column('is_breastfeeding', sa.Boolean(), nullable=False),
    sa.Column('takes_medications', sa.Boolean(), nullable=False),
    sa.Column('medication_list', sa.Text(), nullable=True),
    sa.Column('has_eating_disorder_history', sa.Boolean(), nullable=False),
    sa.Column('other_conditions_text', sa.Text(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('can_proceed', sa.Boolean(), nullable=False),
    sa.Column('requires_professional', sa.Boolean(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('professional_referral_reasons', sa.JSON(), nullable=True),
    sa.Column('recommended_specialists', sa.JSON(), nullable=True),
    sa.Column('parental_consent_email', sa.String(length=255), nullable=True),
    sa.Column('parental_consent_token', sa.String(length=36), nullable=True),
    sa.Column('parental_consent_verified', sa.Boolean(), nullable=False),
    sa.Column('parental_consent_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepts_disclaimer', sa.Boolean(), nullable=False),
    sa.Column('disclaimer_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('client_platform', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parental_consent_token')
    )
    op.create_index(op.f('ix_nutrition_safety_screenings_gym_id'), 'nutrition_safety_screenings', ['gym_id'], unique=False)
    op.create_index(op.f('ix_nutrition_safety_screenings_id'), 'nutrition_safety_screenings', ['id'], unique=False)
    op.create_index(op.f('ix_nutrition_safety_screenings_risk_level'), 'nutrition_safety_screenings', ['risk_level'], unique=False)
    op.create_index(op.f('ix_nutrition_safety_screenings_user_id'), 'nutrition_safety_screenings', ['user_id'], unique=False)

    op.create_table('nutrition_safety_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gym_id', sa.Integer(), nullable=False),
    sa.Column('screening_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('action_details', sa.JSON(), nullable=True),
    sa.Column('was_allowed', sa.Boolean(), nullable=False),
    sa.Column('denial_reason', sa.Text(), nullable=True),
    sa.Column('generated_plan_id', sa.Integer(), nullable=True),
    sa.Column('ai_model_used', sa.String(length=50), nullable=True),
    sa.Column('ai_prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('ai_response_summary', sa.Text(), nullable=True),
    sa.Column('ai_cost_estimate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['generated_plan_id'], ['nutrition_plans.id'], ),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ),
    sa.ForeignKeyConstraint(['screening_id'], ['nutrition_safety_screenings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrition_safety_audit_logs_gym_id'), 'nutrition_safety_audit_logs', ['gym_id'], unique=False)
    op.create_index(op.f('ix_nutrition_safety_audit_logs_id'), 'nutrition_safety_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_nutrition_safety_audit_logs_user_id'), 'nutrition_safety_audit_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nutrition_safety_audit_logs_user_id'), table_name='nutrition_safety_audit_logs')
    op.drop_index(op.f('ix_nutrition_safety_audit_logs_id'), table_name='nutrition_safety_audit_logs')
    op.drop_index(op.f('ix_nutrition_safety_audit_logs_gym_id'), table_name='nutrition_safety_audit_logs')
    op.drop_table('nutrition_safety_audit_logs')
    op.drop_index(op.f('ix_nutrition_safety_screenings_user_id'), table_name='nutrition_safety_screenings')
    op.drop_index(op.f('ix_nutrition_safety_screenings_risk_level'), table_name='nutrition_safety_screenings')
    op.drop_index(op.f('ix_nutrition_safety_screenings_id'), table_name='nutrition_safety_screenings')
    op.drop_index(op.f('ix_nutrition_safety_screenings_gym_id'), table_name='nutrition_safety_screenings')
    op.drop_table('nutrition_safety_screenings')
    # ### end Alembic commands ###