"""Add gym_id field to Class model

Revision ID: e3a222984865
Revises: be94cc40ade3
Create Date: 2025-04-09 02:03:58.362682

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e3a222984865'
down_revision = 'be94cc40ade3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Primero agregamos la columna como nullable
    op.add_column('class', sa.Column('gym_id', sa.Integer(), nullable=True))
    
    # Actualizamos todos los registros existentes con gym_id = 1
    op.execute("UPDATE \"class\" SET gym_id = 1")
    
    # Hacemos la columna NOT NULL después de actualizarla
    op.alter_column('class', 'gym_id', nullable=False)
    
    # Agregamos la clave foránea
    op.create_foreign_key(None, 'class', 'gyms', ['gym_id'], ['id'])
    
    # Continuamos con el resto de las operaciones
    op.drop_index('ix_class_category_custom_gym_id', table_name='class_category_custom')
    op.drop_constraint('fk_class_category_custom_gym_id', 'class_category_custom', type_='foreignkey')
    op.create_foreign_key(None, 'class_category_custom', 'gyms', ['gym_id'], ['id'])
    op.drop_constraint('fk_event_participations_gym_id', 'event_participations', type_='foreignkey')
    op.create_foreign_key(None, 'event_participations', 'gyms', ['gym_id'], ['id'])
    op.drop_index('ix_events_title', table_name='events')
    op.create_index('ix_events_creator_gym', 'events', ['creator_id', 'gym_id'], unique=False)
    op.create_index(op.f('ix_events_creator_id'), 'events', ['creator_id'], unique=False)
    op.create_index(op.f('ix_events_end_time'), 'events', ['end_time'], unique=False)
    op.create_index('ix_events_gym_dates', 'events', ['gym_id', 'start_time', 'end_time'], unique=False)
    op.create_index('ix_events_gym_status', 'events', ['gym_id', 'status'], unique=False)
    op.create_index(op.f('ix_events_start_time'), 'events', ['start_time'], unique=False)
    op.create_index(op.f('ix_events_status'), 'events', ['status'], unique=False)
    op.drop_constraint('fk_events_gym_id', 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'gyms', ['gym_id'], ['id'])
    op.create_index(op.f('ix_gyms_id'), 'gyms', ['id'], unique=False)
    
    op.create_index(op.f('ix_user_gyms_id'), 'user_gyms', ['id'], unique=False)
    op.drop_constraint('user_gyms_gym_id_fkey', 'user_gyms', type_='foreignkey')
    op.drop_constraint('user_gyms_user_id_fkey', 'user_gyms', type_='foreignkey')
    op.create_foreign_key(None, 'user_gyms', 'gyms', ['gym_id'], ['id'])
    op.create_foreign_key(None, 'user_gyms', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_gyms', type_='foreignkey')
    op.drop_constraint(None, 'user_gyms', type_='foreignkey')
    op.create_foreign_key('user_gyms_user_id_fkey', 'user_gyms', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('user_gyms_gym_id_fkey', 'user_gyms', 'gyms', ['gym_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_user_gyms_id'), table_name='user_gyms')
    
    op.drop_index(op.f('ix_gyms_id'), table_name='gyms')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key('fk_events_gym_id', 'events', 'gyms', ['gym_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_events_status'), table_name='events')
    op.drop_index(op.f('ix_events_start_time'), table_name='events')
    op.drop_index('ix_events_gym_status', table_name='events')
    op.drop_index('ix_events_gym_dates', table_name='events')
    op.drop_index(op.f('ix_events_end_time'), table_name='events')
    op.drop_index(op.f('ix_events_creator_id'), table_name='events')
    op.drop_index('ix_events_creator_gym', table_name='events')
    op.create_index('ix_events_title', 'events', ['title'], unique=False)
    op.drop_constraint(None, 'event_participations', type_='foreignkey')
    op.create_foreign_key('fk_event_participations_gym_id', 'event_participations', 'gyms', ['gym_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'class_category_custom', type_='foreignkey')
    op.create_foreign_key('fk_class_category_custom_gym_id', 'class_category_custom', 'gyms', ['gym_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_class_category_custom_gym_id', 'class_category_custom', ['gym_id'], unique=False)
    op.drop_constraint(None, 'class', type_='foreignkey')
    op.drop_column('class', 'gym_id')
    # ### end Alembic commands ### 