"""add_user_gym_subscriptions_table

Revision ID: ea4b311a45fb
Revises: b0f5a7507642
Create Date: 2025-07-11 00:51:59.256351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea4b311a45fb'
down_revision = 'b0f5a7507642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_gym_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_gym_stripe_profile_id', sa.Integer(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['membership_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_gym_stripe_profile_id'], ['user_gym_stripe_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_subscription_id', name='uq_stripe_subscription_id')
    )
    op.create_index('idx_user_gym_subscriptions_created', 'user_gym_subscriptions', ['created_at'], unique=False)
    op.create_index('idx_user_gym_subscriptions_plan', 'user_gym_subscriptions', ['plan_id'], unique=False)
    op.create_index('idx_user_gym_subscriptions_profile_status', 'user_gym_subscriptions', ['user_gym_stripe_profile_id', 'status'], unique=False)
    op.create_index(op.f('ix_user_gym_subscriptions_id'), 'user_gym_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_user_gym_subscriptions_plan_id'), 'user_gym_subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_user_gym_subscriptions_stripe_subscription_id'), 'user_gym_subscriptions', ['stripe_subscription_id'], unique=True)
    op.create_index(op.f('ix_user_gym_subscriptions_user_gym_stripe_profile_id'), 'user_gym_subscriptions', ['user_gym_stripe_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_gym_subscriptions_user_gym_stripe_profile_id'), table_name='user_gym_subscriptions')
    op.drop_index(op.f('ix_user_gym_subscriptions_stripe_subscription_id'), table_name='user_gym_subscriptions')
    op.drop_index(op.f('ix_user_gym_subscriptions_plan_id'), table_name='user_gym_subscriptions')
    op.drop_index(op.f('ix_user_gym_subscriptions_id'), table_name='user_gym_subscriptions')
    op.drop_index('idx_user_gym_subscriptions_profile_status', table_name='user_gym_subscriptions')
    op.drop_index('idx_user_gym_subscriptions_plan', table_name='user_gym_subscriptions')
    op.drop_index('idx_user_gym_subscriptions_created', table_name='user_gym_subscriptions')
    op.drop_table('user_gym_subscriptions')
    # ### end Alembic commands ### 