"""add override_capacity column to class_session

Revision ID: eb04b46638c6
Revises: 402f9b8ef40e
Create Date: 2025-04-18 20:33:37.174310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb04b46638c6'
down_revision = '402f9b8ef40e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_session', sa.Column('override_capacity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('class_session', 'override_capacity')
    # ### end Alembic commands ### 