"""add_super_admin_role

Revision ID: fc6eb1818724
Revises: abca9341c054
Create Date: 2025-04-11 15:03:34.953693

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fc6eb1818724'
down_revision = 'abca9341c054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Crear temporalmente un nuevo enum con el valor SUPER_ADMIN
    userrole_new = postgresql.ENUM('SUPER_ADMIN', 'ADMIN', 'TRAINER', 'MEMBER', name='userrole_new')
    userrole_new.create(op.get_bind())
    
    # Actualizar la columna para usar el nuevo enum
    # Primero modificamos el valor predeterminado para que no haya conflictos
    op.execute('ALTER TABLE "user" ALTER COLUMN role DROP DEFAULT')
    
    # Convertir datos del enum viejo al nuevo
    op.execute((
        "ALTER TABLE \"user\" ALTER COLUMN role TYPE userrole_new USING "
        "CASE role "
            "WHEN 'ADMIN' THEN 'ADMIN'::userrole_new "
            "WHEN 'TRAINER' THEN 'TRAINER'::userrole_new "
            "WHEN 'MEMBER' THEN 'MEMBER'::userrole_new "
        "END"
    ))
    
    # Eliminar el enum viejo
    op.execute('DROP TYPE userrole')
    
    # Renombrar el nuevo enum
    op.execute('ALTER TYPE userrole_new RENAME TO userrole')
    
    # Restaurar el valor predeterminado
    op.execute('ALTER TABLE "user" ALTER COLUMN role SET DEFAULT \'MEMBER\'::userrole')
    
    # ### end Alembic commands ###
    
    # No incluimos cambios para birth_date ya que fue detectado incorrectamente


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Crear temporalmente un nuevo enum sin SUPER_ADMIN
    userrole_old = postgresql.ENUM('ADMIN', 'TRAINER', 'MEMBER', name='userrole_old')
    userrole_old.create(op.get_bind())
    
    # Actualizar usuarios con rol SUPER_ADMIN a ADMIN
    op.execute("UPDATE \"user\" SET role = 'ADMIN' WHERE role = 'SUPER_ADMIN'")
    
    # Actualizar la columna para usar el enum antiguo
    op.execute('ALTER TABLE "user" ALTER COLUMN role DROP DEFAULT')
    
    # Convertir datos del enum nuevo al viejo
    op.execute((
        "ALTER TABLE \"user\" ALTER COLUMN role TYPE userrole_old USING "
        "CASE role "
            "WHEN 'ADMIN' THEN 'ADMIN'::userrole_old "
            "WHEN 'TRAINER' THEN 'TRAINER'::userrole_old "
            "WHEN 'MEMBER' THEN 'MEMBER'::userrole_old "
        "END"
    ))
    
    # Eliminar el enum nuevo
    op.execute('DROP TYPE userrole')
    
    # Renombrar el enum antiguo
    op.execute('ALTER TYPE userrole_old RENAME TO userrole')
    
    # Restaurar el valor predeterminado
    op.execute('ALTER TABLE "user" ALTER COLUMN role SET DEFAULT \'MEMBER\'::userrole')
    # ### end Alembic commands ### 