"""add_gym_id_to_chat_rooms

Revision ID: fcef249f3cff
Revises: a091ab4089d2
Create Date: 2025-06-24 21:41:58.501718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcef249f3cff'
down_revision = 'a091ab4089d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Paso 1: Agregar columna como nullable
    op.add_column('chat_rooms', sa.Column('gym_id', sa.Integer(), nullable=True))
    
    # Paso 2: Asignar gym_id=1 (gimnasio por defecto) a todas las salas existentes
    op.execute("UPDATE chat_rooms SET gym_id = 1 WHERE gym_id IS NULL")
    
    # Paso 3: Hacer la columna NOT NULL
    op.alter_column('chat_rooms', 'gym_id', nullable=False)
    
    # Paso 4: Crear índices y foreign key
    op.create_index(op.f('ix_chat_rooms_gym_id'), 'chat_rooms', ['gym_id'], unique=False)
    op.create_index('ix_chat_rooms_gym_id_status', 'chat_rooms', ['gym_id', 'status'], unique=False)
    op.create_foreign_key(None, 'chat_rooms', 'gyms', ['gym_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_rooms', type_='foreignkey')
    op.drop_index('ix_chat_rooms_gym_id_status', table_name='chat_rooms')
    op.drop_index(op.f('ix_chat_rooms_gym_id'), table_name='chat_rooms')
    op.drop_column('chat_rooms', 'gym_id')
    # ### end Alembic commands ### 